'use strict';

/**
 * Sanitize — Safe HTML Template Utilities
 * Fusion ERP v1.0
 *
 * Provides tagged template literals for safe HTML construction,
 * preventing XSS by auto-escaping all interpolated expressions.
 *
 * Usage:
 *   const name = '<script>alert("xss")</script>';
 *   container.innerHTML = html`<div class="user">${name}</div>`;
 *   // → <div class="user">&lt;script&gt;alert(&quot;xss&quot;)&lt;/script&gt;</div>
 *
 * To insert pre-escaped/trusted HTML, wrap it with raw():
 *   container.innerHTML = html`<div>${raw(trustedHtmlString)}</div>`;
 */

/**
 * Marker class for trusted (pre-escaped) HTML strings.
 * @private
 */
class SafeHTML {
    constructor(html) {
        /** @type {string} */
        this.html = html;
    }
    toString() {
        return this.html;
    }
}

/**
 * Mark a string as trusted/pre-escaped HTML.
 * Use this ONLY for HTML that has already been properly escaped or
 * is generated by trusted code (e.g., icon SVGs, Utils.badge()).
 *
 * @param {string} htmlString - Pre-escaped HTML
 * @returns {SafeHTML}
 *
 * @example
 *   const icon = raw('<i class="fas fa-check"></i>');
 *   container.innerHTML = html`<div>${icon} Done</div>`;
 */
function raw(htmlString) {
    return new SafeHTML(String(htmlString ?? ''));
}

/**
 * Tagged template literal for safe HTML construction.
 * All interpolated values are automatically escaped via Utils.escapeHtml().
 * Use raw() to insert pre-trusted HTML.
 *
 * @param {TemplateStringsArray} strings - Static template parts
 * @param {...any} values - Interpolated values (auto-escaped)
 * @returns {string} Safe HTML string
 *
 * @example
 *   // User input is escaped automatically
 *   const userInput = '<img src=x onerror=alert(1)>';
 *   el.innerHTML = html`<p>${userInput}</p>`;
 *   // → <p>&lt;img src=x onerror=alert(1)&gt;</p>
 *
 *   // Trusted HTML passes through
 *   const badge = raw(Utils.badge('Active', 'green'));
 *   el.innerHTML = html`<div>${badge}</div>`;
 */
function html(strings, ...values) {
    return strings.reduce((result, str, i) => {
        if (i >= values.length) return result + str;

        const val = values[i];

        // TrustedHTML passes through without escaping
        if (val instanceof SafeHTML) {
            return result + str + val.html;
        }

        // Arrays are joined (each element escaped)
        if (Array.isArray(val)) {
            const escaped = val.map(v =>
                v instanceof SafeHTML ? v.html : Utils.escapeHtml(String(v ?? ''))
            ).join('');
            return result + str + escaped;
        }

        // Everything else is escaped
        return result + str + Utils.escapeHtml(String(val ?? ''));
    }, '');
}

// Export to global scope
window.html = html;
window.raw = raw;
