#!/usr/bin/env python3
"""
CSS Builder — Concatenates modular CSS files into a single production bundle.
The split files in css/base/, css/components/, css/modules/ are the source of truth.
This script regenerates css/style_v2.css for production use (single HTTP request).

Usage: python3 scripts/dev/css_build.py
"""

import os

BASE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CSS_DIR = os.path.join(BASE, "css")
ENTRY = os.path.join(CSS_DIR, "style.css")
OUTPUT = os.path.join(CSS_DIR, "style_v2.css")

# Parse the @import order from style.css
imports = []
with open(ENTRY, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line.startswith("@import"):
            # Extract path from @import url('path');
            start = line.index("'") + 1
            end = line.rindex("'")
            path = line[start:end]
            imports.append(path)

print(f"[CSS Builder] Found {len(imports)} imports in style.css")

# Concatenate all files
parts = []
parts.append("/* ═══════════════════════════════════════════════════════════════════════════")
parts.append("   Fusion ERP — Production CSS Bundle")
parts.append("   AUTO-GENERATED by scripts/dev/css_build.py — DO NOT EDIT DIRECTLY")
parts.append("   Edit the source files in css/base/, css/components/, css/modules/ instead.")
parts.append("   ════════════════════════════════════════════════════════════════════════════ */\n")

for imp in imports:
    filepath = os.path.join(CSS_DIR, imp)
    if not os.path.exists(filepath):
        print(f"  ⚠️  Missing: {imp}")
        continue
    
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read().strip()
    
    parts.append(f"\n/* ═══ {imp} ═══ */\n")
    parts.append(content)
    print(f"  ✅ {imp}")

bundle = "\n".join(parts) + "\n"

with open(OUTPUT, "w", encoding="utf-8") as f:
    f.write(bundle)

size_kb = len(bundle.encode("utf-8")) / 1024
print(f"\n✅ Built {OUTPUT}")
print(f"   Size: {size_kb:.1f} KB ({len(imports)} files concatenated)")
